@startuml Flow
!theme materia
skinparam defaultFontName Verdana
' (Alt+D to Preview in VSCode..)

/'
Check out:

https://github.com/conda/conda/tree/master/docs/source/umls
https://github.com/plantuml-stdlib/C4-PlantUML 

Full Docs:
https://plantuml.com/
for more examples

'/

' TODO: LATER EMBED THIS DIAGRAM IN RST..
' Check Conda Docs, How they have done this..

left to right direction

title High Level Flows

' skinparam sequenceMessageAlign center
' Alice -> Bob : Hi
' Bob -> Alice : This is very long
/'
(Code) -> (Local System)
(Code) -> (Github)
(Github) -> (CircleCI)
(CircleCI) -> (Heroku) : Yaml-File
'/
'left to right direction
'top to bottom direction



rectangle Code
rectangle "Local System" as Local_System
rectangle Github
rectangle CircleCI_Machine
rectangle "Docker Hub" as Docker_Hub
rectangle Heroku


Code --> Local_System : Main.py
Code --> Local_System : Docker-Run
Code --> Github : Git Push
Github --> CircleCI_Machine : Push : Fetched By CircleCI
CircleCI_Machine --> CircleCI_Machine : Dockerize
CircleCI_Machine --> Docker_Hub : Docker Image
CircleCI_Machine --> Heroku : Docker Image

/'
' Class..
class Example {
  Sam, Hii   
}
'/


@enduml